
### Create a new note
POST http://localhost:3000/note-book
Content-Type: application/json


{

  "title": "code",
   "created": "2022-3-8",
   "content":"javascript algorithm"
}



###

### Get all books
GET http://localhost:3000/books

###

### Get only available books
GET http://localhost:3000/books?available=true

###

### Get a single book by ID
GET http://localhost:3000/books/1

###

### Update a book
PATCH http://localhost:3000/books
Content-Type: application/json

{
  "availableCopies": 9,
  "title": "Power Book II: Rariq"
}

###

### Soft delete a book (mark unavailable)
DELETE http://localhost:3000/books/

###

### Permanently delete a book
DELETE http://localhost:3000/books/1
