GET  http://localhost:3000

### Create a note
POST http://localhost:3000/note-book
Content-Type: application/json

{
  "title": "prepps",
  "created_at": "2022-03-30",
  "content": "javascrooipt hdh"
}

###

### Get all notes 
GET http://localhost:3000/note-book

###

### Get a single book by ID
GET http://localhost:3000/note-book/1


###

### Update a book
PATCH http://localhost:3000/note-book/1
Content-Type: application/json

{
  "title": "Power Book II: Tariq",
  "content": "Updated content here"
}



###

### Delete
DELETE http://localhost:3000/note-book/1

