
### Create a new note
POST http://localhost:3000/note-book
Content-Type: application/json


{

  "title": "code",
   "created": "2022-3-8",
   "content":"javascript algorithm"
}



###

### Get all notes 
GET http://localhost:3000/note-book

###


###

### Get a single book by ID
GET http://localhost:3000/note-book

###

### Update a book
PATCH http://localhost:3000/note-book
Content-Type: application/json

{
  "availableCopies": 9,
  "title": "Power Book II: Rariq"
}

###



### Delete
DELETE http://localhost:3000/note-book
